/**
 * SF Symbol → Material Symbol, curated by hand.
 *
 * **Partial by nature, and that is the honest description rather than an apology.** SF Symbols has
 * some six thousand names and Material Symbols about four thousand; they overlap in meaning, never
 * in naming, and for plenty of concepts one set simply has no member. An automated mapping would
 * be wrong more often than it was right and would be wrong *silently*, which is the worst
 * property an icon can have — a missing glyph reads as a layout bug, not as a missing icon.
 *
 * So this covers the names real apps actually use, an unmapped name renders nothing and warns once
 * in `__DEV__`, and `RowSpec.materialSymbol` is the escape hatch for everything else.
 *
 * Every value is validated against the shipped `.codepoints` file when the generator runs, so a
 * typo here fails `npm run gen` rather than shipping a blank row.
 */

/** The names the example app uses, which is the set with the strongest claim to being real. */
export const SF_TO_MATERIAL = {
  // --- the example app -------------------------------------------------------------------------
  airplane: 'airplanemode_active',
  alarm: 'alarm',
  'antenna.radiowaves.left.and.right': 'settings_input_antenna',
  'arrow.down.app.fill': 'download',
  'bell.badge.fill': 'notifications',
  book: 'book',
  'brain.head.profile': 'psychology',
  calendar: 'calendar_month',
  'calendar.badge.clock': 'event',
  'camera.fill': 'photo_camera',
  checklist: 'checklist',
  'circle.dashed': 'radio_button_unchecked',
  clock: 'schedule',
  'creditcard.fill': 'credit_card',
  'ellipsis.circle': 'more_horiz',
  'envelope.fill': 'mail',
  exclamationmark: 'priority_high',
  'exclamationmark.2': 'priority_high',
  'exclamationmark.3': 'priority_high',
  'exclamationmark.circle': 'error',
  'figure.mind.and.body': 'self_improvement',
  'figure.wave.circle.fill': 'waving_hand',
  flag: 'flag',
  gear: 'settings',
  'hand.raised.fill': 'pan_tool',
  'heart.fill': 'favorite',
  hourglass: 'hourglass_empty',
  'key.fill': 'vpn_key',
  'list.bullet.clipboard': 'assignment',
  magnifyingglass: 'search',
  'moon.fill': 'dark_mode',
  network: 'lan',
  'note.text': 'description',
  'person.crop.circle.fill': 'account_circle',
  personalhotspot: 'wifi_tethering',
  'photo.fill': 'image',
  'photo.stack.fill': 'photo_library',
  'rectangle.bottomhalf.filled': 'video_label',
  'rectangle.stack': 'layers',
  sparkles: 'auto_awesome',
  'speaker.wave.3.fill': 'volume_up',
  'square.and.pencil': 'edit',
  'square.grid.2x2.fill': 'grid_view',
  'sun.horizon': 'wb_twilight',
  'sun.max': 'light_mode',
  'switch.2': 'toggle_on',
  'textformat.size': 'format_size',
  trash: 'delete',
  wifi: 'wifi',

  // --- the rest of what a settings or list screen reaches for -----------------------------------
  bluetooth: 'bluetooth',
  'chevron.right': 'chevron_right',
  checkmark: 'check',
  xmark: 'close',
  plus: 'add',
  minus: 'remove',
  'arrow.left': 'arrow_back',
  'arrow.right': 'arrow_forward',
  house: 'home',
  'house.fill': 'home',
  person: 'person',
  'person.fill': 'person',
  'person.2': 'group',
  'person.2.fill': 'group',
  star: 'star',
  'star.fill': 'star',
  'square.and.arrow.up': 'share',
  lock: 'lock',
  'lock.fill': 'lock',
  'lock.open': 'lock_open',
  eye: 'visibility',
  'eye.slash': 'visibility_off',
  'bell.slash': 'notifications_off',
  phone: 'phone',
  'phone.fill': 'phone',
  video: 'videocam',
  mic: 'mic',
  'mic.slash': 'mic_off',
  play: 'play_arrow',
  'play.fill': 'play_arrow',
  pause: 'pause',
  stop: 'stop',
  'forward.end': 'skip_next',
  'backward.end': 'skip_previous',
  'arrow.clockwise': 'refresh',
  'arrow.triangle.2.circlepath': 'sync',
  cloud: 'cloud',
  'icloud.and.arrow.down': 'cloud_download',
  'icloud.and.arrow.up': 'cloud_upload',
  folder: 'folder',
  'folder.fill': 'folder',
  doc: 'insert_drive_file',
  'doc.fill': 'insert_drive_file',
  link: 'link',
  paperclip: 'attach_file',
  'doc.on.doc': 'content_copy',
  'doc.on.clipboard': 'content_paste',
  'arrow.uturn.backward': 'undo',
  'arrow.uturn.forward': 'redo',
  'plus.magnifyingglass': 'zoom_in',
  'minus.magnifyingglass': 'zoom_out',
  'arrow.up.left.and.arrow.down.right': 'fullscreen',
  'line.3.horizontal': 'menu',
  'square.grid.3x3': 'apps',
  'list.bullet': 'list',
  'square.grid.2x2': 'dashboard',
  cart: 'shopping_cart',
  'creditcard': 'payment',
  'doc.text': 'receipt',
  storefront: 'storefront',
  tag: 'local_offer',
  map: 'map',
  mappin: 'place',
  'location.north': 'navigation',
  safari: 'explore',
  globe: 'public',
  character: 'language',
  'globe.badge.chevron.backward': 'translate',
  'figure.roll': 'accessibility',
  'questionmark.circle': 'help',
  'info.circle': 'info',
  'exclamationmark.triangle': 'warning',
  'checkmark.circle': 'check_circle',
  'xmark.circle': 'cancel',
  'nosign': 'block',
  'flag.fill': 'report',
  hand: 'thumb_up',
  'hand.thumbsup': 'thumb_up',
  'hand.thumbsdown': 'thumb_down',
  'bubble.left': 'chat',
  'bubble.left.and.bubble.right': 'forum',
  paperplane: 'send',
  'paperplane.fill': 'send',
  tray: 'inbox',
  'tray.full': 'drafts',
  archivebox: 'archive',
  'tag.fill': 'label',
  bookmark: 'bookmark',
  'clock.arrow.circlepath': 'history',
  'calendar.day.timeline.left': 'today',
  'calendar.badge.plus': 'date_range',
  timer: 'timer',
  'alarm.fill': 'alarm_on',
  'arrow.down.circle': 'update',
  'sun.max.fill': 'brightness_high',
  'sun.min': 'brightness_low',
  'circle.lefthalf.filled': 'contrast',
  paintpalette: 'palette',
  paintbrush: 'brush',
  eyedropper: 'colorize',
  bold: 'format_bold',
  italic: 'format_italic',
  'slider.horizontal.3': 'tune',
  hammer: 'build',
  'puzzlepiece.extension': 'extension',
  chevronLeftSlashChevronRight: 'code',
  terminal: 'terminal',
  ant: 'bug_report',
  atom: 'science',
  'plus.forwardslash.minus': 'calculate',
  function: 'functions',
  battery100: 'battery_full',
  'chart.bar': 'signal_cellular_alt',
  'airplane.circle': 'airplanemode_inactive',
  'moon.zzz': 'do_not_disturb_on',
  'moon.stars': 'nightlight',
  'speaker.slash': 'volume_off',
  'speaker.wave.1': 'volume_down',
  headphones: 'headphones',
  hifispeaker: 'speaker',
  'music.note.list': 'album',
  'music.note': 'queue_music',
  'music.quarternote.3': 'library_music',
  'touchid': 'fingerprint',
  'lock.shield': 'security',
  shield: 'shield',
  'checkmark.shield': 'verified_user',
  'network.badge.shield.half.filled': 'vpn_lock',
  key: 'key',
  'rectangle.and.pencil.and.ellipsis': 'password',
  'arrow.up.arrow.down': 'sort',
  'line.3.horizontal.decrease': 'filter_list',
  'arrow.up.and.down': 'swap_vert',
  ellipsis: 'more_vert',
  'chevron.down': 'expand_more',
  'chevron.up': 'expand_less',
  'chevron.left.to.line': 'first_page',
  'chevron.right.to.line': 'last_page',
  qrcode: 'qr_code',
  printer: 'print',
  'doc.viewfinder': 'scanner',
  'laptopcomputer.and.iphone': 'devices',
  iphone: 'smartphone',
  ipad: 'tablet',
  laptopcomputer: 'laptop',
  'tv.fill': 'tv',
  applewatch: 'watch',
  'fork.knife': 'restaurant',
  'cup.and.saucer': 'local_cafe',
  dumbbell: 'fitness_center',
  'figure.run': 'directions_run',
  'figure.walk': 'directions_walk',
  bicycle: 'pedal_bike',
  'sun.min.fill': 'sunny',
  'cloud.fill': 'cloudy',
  'cloud.rain': 'rainy',
  snowflake: 'ac_unit',
  drop: 'water_drop',
  thermometer: 'thermostat',
  wind: 'air',
}

/**
 * Extra Material Symbols to keep in the subset font beyond what the map above references.
 *
 * The font ships **subset**, because the full variable face is 15 MB — enough to dominate a
 * consuming app's download for an icon set most of which it will never draw. Subsetting to the
 * mapped names alone would make `materialSymbol` an escape hatch that mostly escapes to nothing,
 * so this widens it to the icons an Android app is most likely to ask for by name.
 *
 * A `materialSymbol` outside the subset renders nothing and warns, exactly as an unmapped
 * `systemImage` does — the same degradation, documented in the same place.
 */
export const EXTRA_MATERIAL_SYMBOLS = [
  'account_balance', 'add_circle', 'analytics', 'apartment', 'article', 'auto_stories',
  'backup', 'badge', 'bar_chart', 'bedtime', 'bolt', 'campaign', 'cast', 'category',
  'celebration', 'chat_bubble', 'check_box', 'child_care', 'circle', 'cleaning_services',
  'close_fullscreen', 'cookie', 'copyright', 'currency_exchange', 'dark_mode', 'delete_forever',
  'diamond', 'directions_car', 'do_not_disturb', 'done_all', 'download_done', 'draw',
  'edit_note', 'emoji_emotions', 'engineering', 'error_outline', 'euro', 'face',
  'family_restroom', 'fast_forward', 'favorite_border', 'flight', 'flourescent', 'forest',
  'front_hand', 'gavel', 'gesture', 'grade', 'group_add', 'handshake', 'hearing',
  'hide_source', 'hiking', 'hotel', 'house_siding', 'hub', 'ios_share', 'kitchen',
  'landscape', 'light_mode', 'local_fire_department', 'local_pharmacy', 'lock_reset',
  'loop', 'luggage', 'manage_accounts', 'medication', 'mode_night', 'monitoring',
  'nest_eco_leaf', 'newspaper', 'nights_stay', 'notifications_active', 'offline_bolt',
  'open_in_new', 'outbound', 'park', 'pending', 'pets', 'pin_drop', 'pool', 'power',
  'psychology_alt', 'push_pin', 'query_stats', 'quiz', 'radar', 'recycling', 'redeem',
  'restart_alt', 'reviews', 'rocket_launch', 'route', 'rule', 'savings', 'schedule_send',
  'school', 'settings_accessibility', 'shopping_bag', 'signpost', 'sos', 'spa',
  'sports_esports', 'stacked_line_chart', 'stars', 'storm', 'subject', 'support_agent',
  'swipe', 'sync_alt', 'tab', 'task_alt', 'theaters', 'thermostat_auto', 'title',
  'token', 'toll', 'tour', 'traffic', 'trending_up', 'trophy', 'tsunami', 'unarchive',
  'upcoming', 'verified', 'view_list', 'volunteer_activism', 'wallet', 'warehouse',
  'wash', 'waves', 'wb_sunny', 'workspace_premium', 'wysiwyg', 'yard',
]
